/*
 *  UCF COP3330 Summer 2021 Assignment 2 Solution
 *  Copyright 2021 Gabriel Fernandez
 */

package oop.assignment2.ex33.base;

// Import required operators
import java.util.Scanner;
import java.util.Random;

public class Solution33 {
    // Main function
    public static void main(String[] args) {
        getInputPrintOutput();
    }

    // Get input from the user and print output
    // generated by magic8Ball()
    public static void getInputPrintOutput() {
        System.out.println("What's your question?");
        Scanner in = new Scanner(System.in);
        System.out.print("> ");
        in.nextLine();

        String output = magic8Ball();

        System.out.println(output);
    }

    // Randomize between 0 - 3 and print
    // output accordingly
    public static String magic8Ball() {
        // Declare rand operator and initialize max and
        // answer array
        Random rand = new Random();
        int max = 4;
        String [] answer = new String[4];

        // Populate answer array
        answer[0] = "Yes.";
        answer[1] = "No.";
        answer[2] = "Maybe.";
        answer[3] = "Ask again later.";

        // Do some magic
        int magic = rand.nextInt(max);

        // Return the string at the index of the random
        // number
        return answer[magic];
    }
}
