/*
 *  UCF COP3330 Summer 2021 Assignment 2 Solution
 *  Copyright 2021 Gabriel Fernandez
 */

package oop.assignment2.ex25.base;

public class Main25 {
    // Declare constants, which in this case are the passwords
    // themselves, since the prompt said they were given to us
    private static final String pass1 = "12345";
    private static final String pass2 = "abcdef";
    private static final String pass3 = "abc123xyz";
    private static final String pass4 = "1337h@xor!";

    // Main function
    public static void main(String[] args) {

        // Initialize a new instance of PassValidator
        PassValidator pv = new PassValidator();
        // Pass in the password strings and retrieve the
        // int generated by the passwordValidator function
        int result1 = pv.passwordValidator(pass1);
        int result2 = pv.passwordValidator(pass2);
        int result3 = pv.passwordValidator(pass3);
        int result4 = pv.passwordValidator(pass4);

        // Generate an output depending on what int has been
        // received from the passwordValidator function
        String output1 = getOutput(pass1, result1);
        System.out.println(output1);

        String output2 = getOutput(pass2, result2);
        System.out.println(output2);

        String output3 = getOutput(pass3, result3);
        System.out.println(output3);

        String output4 = getOutput(pass4, result4);
        System.out.println(output4);
    }

    // Print the output statement depending on what in is received
    // from passwordValidator
    // I did try a switch statement initially, wasn't working for some
    // reason
    public static String getOutput(String pass, int result) {
        if (result == 1) {
            return "The password " + "'" + pass + "' is a very weak password.";
        } else if (result == 2) {
            return "The password " + "'" + pass + "' is a very weak password,\n" +
                    "but it meets the character limit.";
        } else if (result == 3) {
            return "The password " + "'" + pass + "' is a weak password.";
        } else if (result == 4) {
            return "The password " + "'" + pass + "' is a weak password,\n" +
                    "but it meets the character limit.";
        } else if (result == 5) {
            return "The password " + "'" + pass + "' is a strong password.";
        } else if (result == 6) {
            return "The password " + "'" + pass + "' is a strong password,\n" +
                    "but it does not meet the character limit.";
        } else if (result == 7) {
            return "The password " + "'" + pass + "' is a very strong password.";
        } else if (result == 8) {
            return "The password " + "'" + pass + "' is a very strong password,\n" +
                    "but it does not meet the character limit.";
        } else {
            return "How the hell did you get here?";
        }
    }
}